"""Add bidding fields to Card model

Revision ID: 070727e30fa1
Revises: 3cfb213d0b25
Create Date: 2024-10-11 13:24:58.590798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070727e30fa1'
down_revision = '3cfb213d0b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buy_out_price', sa.Float(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('highest_bid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('highest_bidder_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bidding_end_time', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('key_highest_bidder', 'users', ['highest_bidder_id'], ['id'])
        batch_op.drop_column('price')

    op.execute("UPDATE cards SET buy_out_price = 0.0 WHERE buy_out_price IS NULL")

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bidding_end_time')
        batch_op.drop_column('highest_bidder_id')
        batch_op.drop_column('highest_bid')
        batch_op.drop_column('buy_out_price')

    # ### end Alembic commands ###
