"""Fix bid relationship

Revision ID: 3060c264335d
Revises: 278b7a9869dd
Create Date: 2024-10-11 16:19:02.595704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3060c264335d'
down_revision = '278b7a9869dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_column('bidder_id')
        batch_op.create_foreign_key('fk_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bidder_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_bidder_id', 'users', ['bidder_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
