"""Add timestamp to cart_items

Revision ID: 3cfb213d0b25
Revises: d89e0fa7021d
Create Date: 2024-10-10 12:09:49.692839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cfb213d0b25'
down_revision = 'd89e0fa7021d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
