"""Fix ambiguous foreign keys

Revision ID: 3db6170c4f64
Revises: 070727e30fa1
Create Date: 2024-10-11 15:02:09.016024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db6170c4f64'
down_revision = '070727e30fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('buy_out_price',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('buy_out_price',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
